### ISSUE TITLE
Monero instead of Swap written

### ISSUE THREAD

**Issue by rushiiMachine** [swap-dev/swap#6]
![Screenshot (171)](https://user-images.githubusercontent.com/33725716/59567298-c2056f00-9020-11e9-957b-49fa593e0e7a.png)
![Screenshot (170)](https://user-images.githubusercontent.com/33725716/59567299-c2056f00-9020-11e9-9fc9-b4ccc5945a08.png)

**Comment by LPHuynh** [comment]
Thanks for the report. I'll see if I can push out a minor release soon 👌 
https://github.com/swap-dev/swap-gui/commit/9ba8182c2fd9111df5635982a2b9bbe310be0088
https://github.com/swap-dev/swap-gui/commit/396d362562aba989bef8417b0275dae9f9f44f3f
